### ISSUE TITLE
Wizard failed on GIT sources

### ISSUE THREAD

**Issue by kostapr** [develersrl/bertos#3]
Wizard failed on Ubuntu 14.04
Below is the content of wizard_error.log

Traceback (most recent call last):

  File "/home/kostap/work/stm32_projects/bertos/wizard/BBoardPage.py", line 66, in isComplete
    preset_path = qvariant_converter.getStringDict(preset_path["info"])

  File "/home/kostap/work/stm32_projects/bertos/wizard/qvariant_converter_old.py", line 68, in getStringDict
    a = str(qvariant.toByteArray())

AttributeError: 'dict' object has no attribute 'toByteArray'

  File "/home/kostap/work/stm32_projects/bertos/wizard/BBoardPage.py", line 66, in isComplete
    preset_path = qvariant_converter.getStringDict(preset_path["info"])

  File "/home/kostap/work/stm32_projects/bertos/wizard/qvariant_converter_old.py", line 68, in getStringDict
    a = str(qvariant.toByteArray())

AttributeError: 'dict' object has no attribute 'toByteArray'

  File "/home/kostap/work/stm32_projects/bertos/wizard/BBoardPage.py", line 121, in updateUi
    info_dict = qvariant_converter.getStringDict(info_dict["info"])

  File "/home/kostap/work/stm32_projects/bertos/wizard/qvariant_converter_old.py", line 68, in getStringDict
    a = str(qvariant.toByteArray())

AttributeError: 'dict' object has no attribute 'toByteArray'

  File "/home/kostap/work/stm32_projects/bertos/wizard/BBoardPage.py", line 66, in isComplete
    preset_path = qvariant_converter.getStringDict(preset_path["info"])

  File "/home/kostap/work/stm32_projects/bertos/wizard/qvariant_converter_old.py", line 68, in getStringDict
    a = str(qvariant.toByteArray())

AttributeError: 'dict' object has no attribute 'toByteArray'

  File "/home/kostap/work/stm32_projects/bertos/wizard/BBoardPage.py", line 66, in isComplete
    preset_path = qvariant_converter.getStringDict(preset_path["info"])

  File "/home/kostap/work/stm32_projects/bertos/wizard/qvariant_converter_old.py", line 68, in getStringDict
    a = str(qvariant.toByteArray())

AttributeError: 'dict' object has no attribute 'toByteArray'

  File "/home/kostap/work/stm32_projects/bertos/wizard/BBoardPage.py", line 121, in updateUi
    info_dict = qvariant_converter.getStringDict(info_dict["info"])

  File "/home/kostap/work/stm32_projects/bertos/wizard/qvariant_converter_old.py", line 68, in getStringDict
    a = str(qvariant.toByteArray())

AttributeError: 'dict' object has no attribute 'toByteArray'

**Comment by atlasoft** [comment]
It works well but it's not commited to the tarball... 

Tks
